version: '3'
services:
  apigateway:
    container_name: docker-fastapi
    restart: always
    build:
      context: APIGateway
      dockerfile: APIGateway.Dockerfile
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
    depends_on:
      - postgres
  postgres:
    restart: always
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:postgres
      - POSTGRES_HOST:postgres
      - POSTGRES_HOST_AUTH_METHOD:trust
      - POSTGRES_ADMIN_USER:admin
      - POSTGRES_ADMIN_PASSWORD:admin


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /bitnami/zookeeper


  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    depends_on:
        - zookeeper
    volumes:
      - /bitnami/kafka

# Service of data recognition
  recognizer:
    restart: always
    build:
      context: recognizer
      dockerfile: recognizer.Dockerfile
    volumes:
      - ./recognizer:/app
    ports:
      - 8001:8001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db

    environment:
      MONGO_INITDB_DATABASE: statistics
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      MONGO_INITDB_ROOT_PORT: 27017










volumes:
  postgres_data:
    driver: local
  mongo: