version: '3'
services:
  app:
    container_name: docker-fastapi
    restart: always
    build: .
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
    depends_on:
      - postgres
  postgres:
    restart: always
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:postgres
      - POSTGRES_HOST:postgres
      - POSTGRES_HOST_AUTH_METHOD:trust
      - POSTGRES_ADMIN_USER:admin
      - POSTGRES_ADMIN_PASSWORD:admin

volumes:
  postgres_data:
    driver: local